from enum import Enum

class ReportIndex(Enum):
    NET_INCOME = "Net Income"
    DEPRECIATION_AND_AMORTIZATION = "Depreciation & Amortization"
    LOSS_GAIN_FROM_SALE_OF_INVESTMENTS = "Loss (Gain) From Sale of Investments"
    STOCK_BASED_COMPENSATION = "Stock-Based Compensation"
    OTHER_OPERATING_ACTIVITIES = "Other Operating Activities"
    CHANGE_IN_ACCOUNTS_RECEIVABLE = "Change in Accounts Receivable"
    CHANGE_IN_INVENTORY = "Change in Inventory"
    CHANGE_IN_ACCOUNTS_PAYABLE = "Change in Accounts Payable"
    CHANGE_IN_OTHER_NET_OPERATING_ASSETS = "Change in Other Net Operating Assets"
    OPERATING_CASH_FLOW = "Operating Cash Flow"
    OPERATING_CASH_FLOW_GROWTH_PERCENT = "Operating Cash Flow Growth (%)"
    CAPITAL_EXPENDITURES = "Capital Expenditures"
    CASH_ACQUISITIONS = "Cash Acquisitions"
    INVESTMENT_IN_SECURITIES = "Investment in Securities"
    OTHER_INVESTING_ACTIVITIES = "Other Investing Activities"
    INVESTING_CASH_FLOW = "Investing Cash Flow"
    LONG_TERM_DEBT_ISSUED = "Long-Term Debt Issued"
    LONG_TERM_DEBT_REPAID = "Long-Term Debt Repaid"
    NET_DEBT_ISSUED_REPAID = "Net Debt Issued (Repaid)"
    ISSUANCE_OF_COMMON_STOCK = "Issuance of Common Stock"
    REPURCHASE_OF_COMMON_STOCK = "Repurchase of Common Stock"
    COMMON_DIVIDENDS_PAID = "Common Dividends Paid"
    OTHER_FINANCING_ACTIVITIES = "Other Financing Activities"
    FINANCING_CASH_FLOW = "Financing Cash Flow"
    NET_CASH_FLOW = "Net Cash Flow"
    FREE_CASH_FLOW = "Free Cash Flow"
    FREE_CASH_FLOW_GROWTH_PERCENT = "Free Cash Flow Growth (%)"
    FREE_CASH_FLOW_MARGIN_PERCENT = "Free Cash Flow Margin (%)"
    FREE_CASH_FLOW_PER_SHARE = "Free Cash Flow Per Share"
    CASH_INTEREST_PAID = "Cash Interest Paid"
    CASH_INCOME_TAX_PAID = "Cash Income Tax Paid"
    LEVERED_FREE_CASH_FLOW = "Levered Free Cash Flow"
    UNLEVERED_FREE_CASH_FLOW = "Unlevered Free Cash Flow"
    CHANGE_IN_WORKING_CAPITAL = "Change in Working Capital"