from enum import Enum

class RatiosIndex(Enum):
    MARKET_CAPITALIZATION = "Market Capitalization"
    MARKET_CAP_GROWTH_PERCENT = "Market Cap Growth (%)"
    ENTERPRISE_VALUE = "Enterprise Value"
    LAST_CLOSE_PRICE = "Last Close Price"
    PE_RATIO = "PE Ratio"
    FORWARD_PE = "Forward PE"
    PS_RATIO = "PS Ratio"
    PB_RATIO = "PB Ratio"
    P_TBV_RATIO = "P/TBV Ratio"
    P_FCF_RATIO = "P/FCF Ratio"
    P_OCF_RATIO = "P/OCF Ratio"
    PEG_RATIO = "PEG Ratio"
    EV_SALES_RATIO = "EV/Sales Ratio"
    EV_EBITDA_RATIO = "EV/EBITDA Ratio"
    EV_EBIT_RATIO = "EV/EBIT Ratio"
    EV_FCF_RATIO = "EV/FCF Ratio"
    DEBT_EQUITY_RATIO = "Debt / Equity Ratio"
    DEBT_EBITDA_RATIO = "Debt / EBITDA Ratio"
    DEBT_FCF_RATIO = "Debt / FCF Ratio"
    ASSET_TURNOVER = "Asset Turnover"
    INVENTORY_TURNOVER = "Inventory Turnover"
    QUICK_RATIO = "Quick Ratio"
    CURRENT_RATIO = "Current Ratio"
    RETURN_ON_EQUITY_ROE_PERCENT = "Return on Equity (ROE) (%)"
    RETURN_ON_ASSETS_ROA_PERCENT = "Return on Assets (ROA) (%)"
    RETURN_ON_CAPITAL_ROIC_PERCENT = "Return on Capital (ROIC) (%)"
    RETURN_ON_CAPITAL_EMPLOYED_ROCE_PERCENT = "Return on Capital Employed (ROCE) (%)"
    EARNINGS_YIELD_PERCENT = "Earnings Yield (%)"
    FCF_YIELD_PERCENT = "FCF Yield (%)"
    DIVIDEND_YIELD_PERCENT = "Dividend Yield (%)"
    PAYOUT_RATIO_PERCENT = "Payout Ratio (%)"
    BUYBACK_YIELD_DILUTION_PERCENT = "Buyback Yield / Dilution (%)"
    TOTAL_SHAREHOLDER_RETURN_PERCENT = "Total Shareholder Return (%)"